Description:
  CapstoneADLRM Infrastructure (Kubernetes and Nodes).

Parameters:
    EnvironmentName:
        Description: Our environment's name, used to import and export infrastructure from other yml files.
        Type: String
        Default: CapstoneADLRM
    ID:
        Description: Unique identifier.
        Type: String
        Default: 01234

Resources:
  EKSNode2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "eks-node2-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Sub "CapstoneADLRM-Cluster-1234"
      NodegroupName: !Sub "CapstoneADLRM-NodeGroup-1234"
      NodeRole: !GetAtt EKSNode2IAMRole.Arn
      Subnets:
      - subnet-00d4ec78f12ee3f4e
      - subnet-0ad313bf4ca8721f4
      ScalingConfig:
        DesiredSize: 1
        MaxSize: 2
        MinSize: 1
      InstanceTypes:
        - "t2.micro"
      Tags:
        kubernetes.io/cluster/CapstoneADLRM-Cluster-1234 : owned